In [1]:
import numpy as np
data=np.random.randint(1,100,(5,5))
data

array([[92, 90, 84,  5, 12],
       [26, 48, 91, 46, 60],
       [33, 53, 35, 70, 82],
       [61, 11, 87, 19, 52],
       [75,  8, 80, 80, 82]], dtype=int32)

In [2]:
type(np.array([1,2,3]))

numpy.ndarray

In [5]:
data
print(" ")
print(data[-3:-1,-3:-1])

 
[[35 70]
 [87 19]]


In [1]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[5, 3, 1],
       [1, 0, 6],
       [8, 8, 6]], dtype=int32)

In [3]:
np.random.randn(30,30).mean()

np.float64(-0.060191140964028056)

In [4]:
np.std(data)

np.float64(2.8974232912011773)

In [5]:
np.mean(data)

np.float64(4.222222222222222)

In [6]:
np.median(data)

np.float64(5.0)

In [8]:
data=np.random.randint(0,100,10)
data

array([ 5, 30, 44, 47, 41, 91, 23, 64, 29,  1], dtype=int32)

In [9]:
data.min(),data.max()

(np.int32(1), np.int32(91))

In [11]:
range=data.max()-data.min()
range

np.int32(90)